version: '3.3'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
      - "8787:8787"
    environment:
      PGUSER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "keycloak"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 1s

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - ./target/keycloak-terms-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-terms-authenticator-1.0-SNAPSHOT.jar

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9000:8080"

volumes:
  postgresql_data:
    driver: local